### ISSUE TITLE
no-extraneous-dependencies not required for React Native

### ISSUE THREAD

**Issue by obipawan** [kunalgolani/eslint-config#3]
React Native's [Image](https://facebook.github.io/react-native/docs/image.html) component allows for using local assets as source using `require`s like 
`<Image source={ require('image!local_asset.png') } />` 
These cannot/shouldn't be declared in package.json

**Comment by kunalgolani** [comment]
https://github.com/benmosher/eslint-plugin-import/issues/340

the correct solution would be to specify a custom resolver: https://github.com/benmosher/eslint-plugin-import/tree/master/resolvers
