### ISSUE TITLE
Update peer dependency to include eslint@^6.0.0

### ISSUE THREAD

**Issue by nul** [kunalgolani/eslint-config#39]
Current version lists as peer dependency eslint@^5.0.0. 

npm WARN eslint-config-esnext@4.0.0 requires a peer of eslint@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-recommended@4.0.0 requires a peer of eslint@^5.0.0 but none is installed. You must install peer dependencies yourself.

Can we bump that to include eslint@^6.0.0?

**Comment by abelkius** [comment]
@kunalgolani is it possible to also increase the version of the package (even the bugfix version would help)? Our registry which is caching those packages isn't picking up this change because the version number didn't change. Thanks!

**Comment by nul** [comment]
bump

**Comment by abelkius** [comment]
bump

**Comment by kunalgolani** [comment]
@nul @abelkius I'm not actively maintaining this project anymore, happy to add you as collaborators so you can take care of it. Let me know if you'd like that.

**Comment by gogoyqj** [comment]
any progress，the version on npm is still 4.0.0

**Comment by nul** [comment]
@kunalgolani I've bumped the versions and prepared the packages, but can't publish to npm due to permissions. Can you add me as a collaborator there as well? (username: alex-raileanu)

**Comment by kunalgolani** [comment]
@nul done for all 4 packages published from this repo. Please close the issue once you're done with the version bump. IIRC there are some package.json scripts in there to help with versioning or publishing, probably some hooks.

**Comment by nul** [comment]
Thanks @kunalgolani. Published version 4.1.0 for all 4 packages. Closing this issue.

**Comment by ndr47** [comment]
Will this be updated to eslint@7.x.x?
