### ISSUE TITLE
npm WARN eslint-config-node@1.6.0 requires a peer of eslint@~3.4.0 but none was installed.

### ISSUE THREAD

**Issue by jerroydmoore** [kunalgolani/eslint-config#4]
The following package.json generates npm warnings. Either this npm module should allow newer versions of eslint, or eslint-config should be updated to maintain parity with eslint.

    npm WARN eslint-config-node@1.6.0 requires a peer of eslint@~3.4.0 but none was installed.
    npm WARN eslint-config-esnext@1.6.0 requires a peer of eslint@~3.4.0 but none was installed.

package.json:
```
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "eslint": "^3.19.0",
    "eslint-config-node": "^1.6.0"
  }
}
```

**Comment by kunalgolani** [comment]
This is now done in #6
