### ISSUE TITLE
Update peer dependency to include eslint@^7.0.0 

### ISSUE THREAD

**Issue by tcamaraCS** [kunalgolani/eslint-config#48]
Current version lists as peer dependency eslint@^6.0.0.

npm WARN eslint-config-node@4.1.0 requires a peer of eslint@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-esnext@4.1.0 requires a peer of eslint@^6.0.0 but none is installed. You must install peer dependencies yourself.

Can we bump that to include eslint@^7.0.0?

**Comment by zevisert** [comment]
@nul I see you became a collaborator for the bump of eslint@6, can you do this one as well?

**Comment by dopry** [comment]
@nul @kunalgolani  I just submitted https://github.com/kunalgolani/eslint-config/pull/50 to fix this

**Comment by amaster507** [comment]
@kunalgolani This says it is merged and closed but I am still experiencing this problem on 4.1.0 did this not make it into that release?
