### ISSUE TITLE
eslint-config-esnext@2.0.0 requires a peer of eslint-plugin-babel@^4.1.2 but none is installed.

### ISSUE THREAD

**Issue by bfanger** [kunalgolani/eslint-config#7]
I'm using `"eslint-plugin-babel": "^5.1.0"` and am not experiencing any issues.

Could you include 5.x  in the peerDependency range?

**Comment by kunalgolani** [comment]
Hey, Bob. Feel free to add it yourself and send a pull request. I'll
version and publish it then.

**Comment by kunalgolani** [comment]
https://github.com/kunalgolani/eslint-config/commit/395678792310a9af3f26c45c8488a65cf239741b should fix this :)

**Comment by kunalgolani** [comment]
Worth noting that this is a major version change, so you'll have to upgrade to `3.0.0` of this dependency.
